filebeat.inputs:
- type: log
  enabled: true
  paths:
  - /var/log/nginx/access.log
  fields:
    log_source: nginx-access
- type: log
  enabled: true
  paths:
  - /var/log/nginx/error.log
  fields:
    log_source: nginx-error
#索引的命名在logstash上操作
output.logstash:
  hosts: ["localhost:5044"]
