apiVersion: v1 
kind: Pod 
metadata:
  name: test-pd 
spec:
  containers:
  - image: hub.atguigu.com/library/myapp:v1 
    name: test-container 
    volumeMounts:
    - mountPath: /cache 
      name: cache-volume
  - name: livene    
    image: busybox    
    imagePullPolicy: IfNotPresent    
    command: ["/bin/sh","-c","sleep 3600s"]    
    volumeMounts:
    - mountPath: /test
      name: cache-volume
  volumes:
  - name: cache-volume 
    emptyDir: {}
