apiVersion: v1 
kind: Pod 
metadata:
  name: test-pd 
spec:
  containers:
  - image: hub.atguigu.com/library/myapp:v1
    name: test-container 
    volumeMounts:
    - mountPath: /test-pd 
      name: test-volume
  volumes:
  - name: test-volume 
    hostPath:
      path: /data
      type: Directory
