apiVersion: extensions/v1beta1 
kind: Ingress
metadata:
  name: https
spec:
  tls:
  - hosts:
    - www3.atguigu.com
    secretName: tls-secret
  rules:
  - host: www3.atguigu.com
    http:
      paths:
      - path: / 
        backend:
          serviceName: svc-3 
          servicePort: 80
