apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: deployment3 
spec:
  replicas: 2 
  template:
    metadata:
      labels:
        name: nginx3 
    spec:
      containers:
      - name: nginx2
        image: wangyanglinux/myapp:v3 
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: svc-3
spec:
  ports:
  - port: 80
    targetPort: 80 
    protocol: TCP
  selector: 
    name: nginx3
