# ======================== Elasticsearch Configuration =========================
#                          静态配置，还有很多动态配置不包含在这里
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please see the documentation for further information on configuration options:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html>
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#集群名称，集群唯一，集群内的节点都是一样的
cluster.name: myes 
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#节点名称，每个节点都不一样
node.name: linux-node1 
#可以被设置为master和data节点
#node.master: true
#node.data: true
# Add custom attributes to the node:
#
# node.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: /data/es-data
#
# Path to log files:
#
path.logs: /var/log/elasticsearch 
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#锁定内存，防止被占用
bootstrap.memory_lock: true
#
# Make sure that the `ES_HEAP_SIZE` environment variable is set to about half the memory
# available on the system and that the owner of the process is allowed to use this limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#通过本机那个ip访问到
network.host: 192.168.3.63
#
# Set a custom port for HTTP:
#
http.port: 9200
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
# discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#单播形式：不是整个局域网机器都发
discovery.zen.ping.unicast.hosts: ["192.168.3.64", "192.168.3.63"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
# 防止脑裂,采用投票方式的最少节点（master节点总数/2+1）
discovery.zen.minimum_master_nodes: 2
#跨域
#http.cors.enabled: true
#http.cors.allow-origin: "*"
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#启动了指定数量启动完成才开始数据恢复，节约带宽，必须达到
# gateway.recover_after_nodes: 3
#预期节点数量,尽力达到
#gateway.expected_node: 5
#凑齐预期节点数量的时间
#gateway.recover_after_time: 5m
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html>
#
# ---------------------------------- Various -----------------------------------
#
# Disable starting multiple nodes on a single system:
#
# node.max_local_storage_nodes: 1
#
# Require explicit names when deleting indices:
#
# action.destructive_requires_name: true

