apiVersion: v1
kind: PersistentVolume 
metadata:
  name: nfspv1 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /nfsdata1 
    server: 192.168.3.70
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /nfsdata2
    server: 192.168.3.70
