apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: deployment1 
spec:
  replicas: 2 
  template:
    metadata:
      labels:
        name: nginx1 
    spec:
      containers:
      - name: nginx
        image: wangyanglinux/myapp:v1 
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: svc-1 
spec:
  ports:
  - port: 80
    targetPort: 80 
    protocol: TCP
  selector: 
    name: nginx1
